version: "2.3"
services:

  python_dev:
    build:
      context: . 
    image: python_dev
    container_name: python_dev
    command: service ssh restart
    command: jupyter notebook --no-browser --allow-root --port 8888 --ip=0.0.0.0 --NotebookApp.token='docker'
    ports:
      - "2222:22"
      - "8001:8888"
    env_file:
      - .env
    volumes:
      - .:/root/Project
    runtime: nvidia
